config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  resources :posts, only: [:index, :show]

  namespace :my do
    resource :post, only: [:new, :create, :edit, :update] do
      member do
        get :preview
        patch :submit
      end
    end
  end

  namespace :admin do
    resources :coupons do
      member do
        get :print
        patch :tag_sended
      end
      collection do
        post :batch_create
        get :bulk_print
      end
    end

    resources :users
    resources :posts do
      member do
        patch :approve
      end
    end

    root "dashboard#index"
  end

  get "vip_lobby", to: "home#vip_lobby"
  get "guide", to: "home#guide"
  post "enter_lobby", to: "home#enter_lobby"

  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_attachments, dependent: :destroy, inverse_of: :post
  accepts_nested_attributes_for :post_attachments, allow_destroy: true, reject_if: :all_blank

  enum status: {
    draft: 0,
    submitted: 1,
    approved: 2
  }

  validates :title, presence: true
  validates :store, presence: true
  validates :comment, presence: true
  validates :moto_type, presence: true

  scope :recent, -> { order(id: :desc) }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all.recent
  end

  def show
    @post = Post.find(params[:id])
    @post_attachments = @post.post_attachments.all
  end

  def approve
    @post = Post.find(params[:id])

    if @post.approved!
      redirect_back(fallback_location: admin_post_path(@post), notice: "PostID: #{@post.id} 更新成功！")
    else
      redirect_back(fallback_location: admin_posts_path, alert: "PostID: #{@post.id} 更新失敗！")
    end
  end
end

app/controllers/my/posts_controller.rb
class My::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update, :preview, :submit]

  def new
    @post = current_user.build_post
    @post.post_attachments.build
  end

  def create
    @post = current_user.build_post(post_params)

    if @post.save
      redirect_to preview_my_post_path, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @post.post_attachments.build if @post.post_attachments.empty?
  end

  def update
    @post.status = "draft"

    if @post.update(post_params)
      redirect_to preview_my_post_path, notice: 'Post was successfully created.'
    else
      render :edit
    end
  end

  def preview
    @post_attachments = @post.post_attachments.all
  end

  def submit
    if @post.update!(status: "submitted")
      redirect_to preview_my_post_path, notice: '已提交審核，請耐心等候。'
    else
      render "preview"
    end
  end

  private

  def find_post
    @post = current_user.post
  end

  def post_params
    params.require(:post).permit(:title, :store, :moto_type, :front_brake_caliper, :front_wheel_rim, :front_shock, :back_brake_caliper, :back_wheel_rim, :back_shock, :drive_line_system, :engine_system, :exhaust_pipe, :appearance, :others, :comment, post_attachments_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def index
    @posts = Post.approved.recent
  end

  def show
    @post_attachments = @post.post_attachments.all
    set_meta_tags title: "#{@post.title} - #{@post.moto_type}",
                  description: @post.comment,
                  keywords: "#{@post.store}, #{@post.front_brake_caliper}, #{@post.front_wheel_rim}, #{@post.front_shock}, #{@post.back_brake_caliper}, #{@post.back_wheel_rim}, #{@post.back_shock}",
                  og: {
                    image: @post_attachments.first.image.og.url
                  }
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/my/post_helper.rb
module My::PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def render_preview_title(post)
    case post.status
    when "draft"
      "草稿"
    when "submitted"
      "已送出"
    when "approved"
      "審核通過"
    else
      "ERROR"
    end
  end

  def render_preview_bar_css_color(post)
    case post.status
    when "draft"
      "bg-secondary"
    when "submitted"
      "bg-warning"
    when "approved"
      "bg-success"
    else
      "bg-info"
    end
  end
end

app/views/my/posts/_form.html.erb
<div class="container">
  <%= simple_form_for(@post, url: my_post_path) do |f| %>
  <div class="row mt-4">
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          基本資訊
        </div>
        <div class="card-body">
          <%= f.input :title, label: "文章標題", placeholder: "ex: 工程師的城市馬" %>
          <%= f.input :moto_type, label: "車的型號", placeholder: "ex: 三代勁戰" %>
          <%= f.input :store, label: "店家或團體名稱", placeholder: "ex: 大便的人不會寂寞" %>
          <%= f.input :comment, label: "車主的話", placeholder: "ex: 想說什麼就說什麼" %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          動力相關
        </div>
        <div class="card-body">
          <%= f.input :drive_line_system, label: "傳動系統", placeholder: "ex: XXXX 傳動" %>
          <%= f.input :engine_system, label: "引擎系統", placeholder: "ex: 可自由填寫詳細清單" %>
          <%= f.input :exhaust_pipe, label: "排氣管", placeholder: "ex: 原廠排氣管" %>
          <br>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          前 & 後總成細項
        </div>
        <div class="card-body">
          <%= f.input :front_brake_caliper, label: "前卡鉗", placeholder: "ex: Banana 基本對四" %>
          <%= f.input :front_wheel_rim, label: "前輪框", placeholder: "ex: Shit factory 鍛造框" %>
          <%= f.input :front_shock, label: "前避震", placeholder: "ex: LP330" %>
          <br>
          <hr>
          <%= f.input :back_brake_caliper, label: "後卡鉗", placeholder: "ex: 鼓煞可不必填寫" %>
          <%= f.input :back_wheel_rim, label: "後輪框", placeholder: "ex: Shit factory 內碟框" %>
          <%= f.input :back_shock, label: "後避震", placeholder: "ex: X6" %>
          <br>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          其他周邊
        </div>
        <div class="card-body">
          <%= f.input :appearance, label: "外觀", placeholder: "ex: 可自由填寫詳細清單" %>
          <%= f.input :others, label: "其他", placeholder: "ex: 可自由填寫詳細清單" %>
          <br>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          圖片區
        </div>
        <div class="card-body">
          <%= f.nested_fields_for :post_attachments do |ff| %>

            <div class="field">
              <%= ff.label "圖片" %><br>
              <%= ff.file_field :image, id: "imgFile" %>
              <%= image_tag(ff.object.new_record? ? "" : ff.object.try(:image).try(:url), class: "img-fluid", id: "pic") %>
            </div>
            <br>
            <%= ff.remove_nested_fields_link "移除圖片", class: "btn btn-danger btn-sm" %>
          <% end %>
          <hr>
          <%= f.add_nested_fields_link :post_attachments, "新增圖片", class: "btn btn-primary btn-sm" %>
          <br>
        </div>
      </div>
    </div>
  </div>

  <%= f.submit "預覽", class: "btn btn-primary" %>

  <% end %>
</div>


<script>
  // Textarea auto resize
  const tx = document.getElementsByTagName("textarea");
  for (let i = 0; i < tx.length; i++) {
    tx[i].setAttribute("style", "height:" + (tx[i].scrollHeight) + "px;overflow-y:hidden;");
    tx[i].addEventListener("input", OnInput, false);
  }

  function OnInput() {
    this.style.height = "auto";
    this.style.height = (this.scrollHeight) + "px";
  }

  // Image upload file prview
  imgFile0.onchange = evt => {
    const [file] = imgFile1.files
    if (file) {
      pic0.src = URL.createObjectURL(file)
    }
  }
  imgFile2.onchange = evt => {
    const [file] = imgFile2.files
    if (file) {
      pic2.src = URL.createObjectURL(file)
    }
  }
  imgFile3.onchange = evt => {
    const [file] = imgFile3.files
    if (file) {
      pic3.src = URL.createObjectURL(file)
    }
  }
  imgFile4.onchange = evt => {
    const [file] = imgFile4.files
    if (file) {
      pic4.src = URL.createObjectURL(file)
    }
  }
  imgFile5.onchange = evt => {
    const [file] = imgFile5.files
    if (file) {
      pic5.src = URL.createObjectURL(file)
    }
  }
</script>

app/views/my/posts/edit.html.erb
<h1 class="text-center">編輯</h1>

<%= render "form" %>

app/views/my/posts/new.html.erb
<%= render "form" %>

app/views/my/posts/preview.html.erb
<% context = [
  "這台來自 #{@post.store} 的 #{@post.moto_type} 想必是車主的寶貝，就讓我們來看看車上動了什麼吧！",
  "前總成使用 #{@post.front_brake_caliper}、#{@post.front_wheel_rim}、#{@post.front_shock}",
  "後面的部分，也不簡單，使用了 #{@post.back_wheel_rim} 的後輪框",
  "以及 #{@post.back_shock} 的避震器來提升整體車輛穩定性",
  "排氣管使用的則是 #{@post.exhaust_pipe}",
  "test",
  "test",
  "test",
  "test"
  ] %>

<div class="container">
  <div class="row py-4">
    <div class="col-md-6 mx-auto">
      <div class="card mb-3">
        <div class="card-header <%= render_preview_bar_css_color(@post) %>"><%= render_preview_title(@post) %></div>
        <div class="card-body">
          <% if @post.draft? %>
            <p class="card-text">目前只有您能看到這篇報導，需送出審核後，經由站方審核後將公開於網站內容</p>
          <% end %>

          <% if @post.submitted? %>
            <p class="card-text">已提交審核，請耐心等候結果，在此之前，您的資訊不會顯示在網站公開頁面</p>
            <p class="card-text">如果您重新編輯，狀態將會退回，需要重新審核</p>
          <% end %>

          <% if @post.approved? %>
            <p class="card-text">您的資訊已審核通過，現在可以在網站公開頁面看見！</p>
          <% end %>
        </div>

        <% if @post.draft? || !@post.submitted? %>
        <div class="card-footer">
          <div>
            <%= link_to("繼續編輯", edit_my_post_path, class: "btn btn-primary btn-sm") if !@post.submitted? %>
            <%= link_to("提交審核", submit_my_post_path, class: "btn btn-success btn-sm", method: :patch) if @post.draft? %>
          </dov>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="col-md-6 mx-auto">
      <h3><%= @post.title %></h3>

      <% @post_attachments.each_with_index do |post_attachment, index| %>
        <%= image_tag(post_attachment.image.url, class: "img-fluid") %>

        <p><%= context[index] %></p>
      <% end %>

    <table class="table table-bordered">
      <tbody>
        <tr>
          <th scope="row">車輛提供</th>
          <td><%= @post.store %></td>
        </tr>

        <tr>
          <th scope="row">傳動系統</th>
          <td><%= simple_format(@post.drive_line_system) %></td>
        </tr>

        <tr>
          <th scope="row">引擎系統</th>
          <td><%= simple_format(@post.engine_system) %></td>
        </tr>

        <tr>
          <th scope="row">外觀</th>
          <td><%= simple_format(@post.appearance) %></td>
        </tr>

        <tr>
          <th scope="row">其他</th>
          <td><%= simple_format(@post.others) %></td>
        </tr>

        <tr>
          <th scope="row">車主的話</th>
          <td><%= simple_format(@post.comment) %></td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>