config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  resources :posts, only: [:index, :show]

  namespace :my do
    resource :post, only: [:new, :create, :edit, :update] do
      member do
        get :preview
        patch :submit
      end
    end
  end

  namespace :admin do
    resources :coupons do
      member do
        get :print
        patch :tag_sended
      end
      collection do
        post :batch_create
        get :bulk_print
      end
    end

    resources :users
    resources :posts do
      member do
        patch :approve
      end
    end

    root "dashboard#index"
  end

  get "vip_lobby", to: "home#vip_lobby"
  get "guide", to: "home#guide"
  post "enter_lobby", to: "home#enter_lobby"

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  include AASM

  enum using_state: {
    initial: 0,
    complete: 1
  }

  belongs_to :user, optional: true

  before_create :generate_code

  aasm column: :using_state, enum: true do # defaults to aasm_state
    state :initial, initial: true
    state :complete

    event :complete do
      transitions to: :complete, from: [:initial]
    end
  end

  scope :recent, -> { order(id: :desc) }

  private

  def generate_code
    self.code = SecureRandom.hex(4).upcase
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_attachments, dependent: :destroy, inverse_of: :post
  accepts_nested_attributes_for :post_attachments, allow_destroy: true, reject_if: :all_blank

  enum status: {
    draft: 0,
    submitted: 1,
    approved: 2
  }

  validates :title, presence: true
  validates :store, presence: true
  validates :comment, presence: true
  validates :moto_type, presence: true

  scope :recent, -> { order(id: :desc) }
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  attr_accessor :coupon

  has_one :post

  scope :recent, -> { order(id: :desc) }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  layout "admin"

  private

  def admin_required
    unless current_user.is_admin?
      redirect_to "/"
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all.recent
  end

  def show
    @post = Post.find(params[:id])
    @post_attachments = @post.post_attachments.all
  end

  def approve
    @post = Post.find(params[:id])

    if @post.approved!
      redirect_back(fallback_location: admin_post_path(@post), notice: "PostID: #{@post.id} 更新成功！")
    else
      redirect_back(fallback_location: admin_posts_path, alert: "PostID: #{@post.id} 更新失敗！")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :coupon) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def vip_lobby
    set_meta_tags title: "VIP 專屬大廳",
                  description: "只有真正的便友，才能進入"
  end

  def guide
    set_meta_tags title: "如何成為便友？",
                  description: "如果只有心中所想，寂寞將在黑夜再次悄然而襲，您必須於蝦皮網站，購買專屬貼紙"
  end

  def enter_lobby
    if Coupon.initial.where(code: params["coupon"]).exists?
      redirect_to new_user_registration_path(coupon: params["coupon"]), notice: "成功進入註冊頁面"
    else
      redirect_back(fallback_location: root_path, alert: "該代碼錯誤或是已被使用。")
    end
  end
end

app/controllers/my/posts_controller.rb
class My::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update, :preview, :submit]

  def new
    @post = current_user.build_post
    @post.post_attachments.build
  end

  def create
    @post = current_user.build_post(post_params)

    if @post.save
      redirect_to preview_my_post_path, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @post.post_attachments.build if @post.post_attachments.empty?
  end

  def update
    @post.status = "draft"

    if @post.update(post_params)
      redirect_to preview_my_post_path, notice: 'Post was successfully created.'
    else
      render :edit
    end
  end

  def preview
    @post_attachments = @post.post_attachments.all
  end

  def submit
    if @post.update!(status: "submitted")
      redirect_to preview_my_post_path, notice: '已提交審核，請耐心等候。'
    else
      render "preview"
    end
  end

  private

  def find_post
    @post = current_user.post
  end

  def post_params
    params.require(:post).permit(:title, :store, :moto_type, :front_brake_caliper, :front_wheel_rim, :front_shock, :back_brake_caliper, :back_wheel_rim, :back_shock, :drive_line_system, :engine_system, :exhaust_pipe, :appearance, :others, :comment, post_attachments_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def index
    @posts = Post.approved.recent
  end

  def show
    @post_attachments = @post.post_attachments.all
    set_meta_tags title: "#{@post.title} - #{@post.moto_type}",
                  description: @post.comment,
                  keywords: "#{@post.store}, #{@post.front_brake_caliper}, #{@post.front_wheel_rim}, #{@post.front_shock}, #{@post.back_brake_caliper}, #{@post.back_wheel_rim}, #{@post.back_shock}",
                  og: {
                    image: @post_attachments.first.image.og.url
                  }
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site:        "NLFS - 便友停機坪",
      description: "大便的人不會寂寞，不只是一個梗、一首歌或是一張貼紙，他凝聚了一群有白爛靈魂的車友，這裡就是便友專屬的停機坪。",
      keywords:    "改裝, 機車, 勁戰, 雷霆",
      # og: {
      #   image: ActionController::Base.helpers.asset_path('logo.png')
      # },
      # fb: {
      #   app_id: "1304370673045470"
      # },
      reverse: true
    }
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my/post_helper.rb
module My::PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def render_preview_title(post)
    case post.status
    when "draft"
      "草稿"
    when "submitted"
      "已送出"
    when "approved"
      "審核通過"
    else
      "ERROR"
    end
  end

  def render_preview_bar_css_color(post)
    case post.status
    when "draft"
      "bg-secondary"
    when "submitted"
      "bg-warning"
    when "approved"
      "bg-success"
    else
      "bg-info"
    end
  end
end

app/views/admin/common/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>

        <%#= image_tag(current_user.avatar.url, class: "img-profile rounded-circle")%>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <%= link_to(root_path, class: "dropdown-item") do %>
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          首頁
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to(destroy_user_session_path, method: :delete, class: "dropdown-item") do %>
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          登出
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/admin/common/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

  <%= link_to(admin_root_path, class: "sidebar-brand d-flex align-items-center justify-content-center") do %>
    <div class="sidebar-brand-text mx-3">NLFS 後台</div>
  <% end %>

  <li class="nav-item active">
    <%= link_to(admin_root_path, class: "nav-link") do %>
      <%= tag.span("首頁") %>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to(admin_users_path, class: "nav-link") do %>
      <%= tag.span("用戶管理") %>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to(admin_coupons_path, class: "nav-link") do %>
      <%= tag.span("序號管理") %>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to(admin_posts_path, class: "nav-link") do %>
      <%= tag.span("文章管理") %>
    <% end %>
  </li>
</ul>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissible alert-<%= flash_class(key) %> fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 h-100 text-center my-auto">
        <p class="text-muted small mb-4 mb-lg-0">© NLFS 便友停機坪 <%= Time.zone.now.year %>. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/common/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1902ZPSST9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1902ZPSST9');
</script>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to("NLFS 便友停機坪", root_path, class: "navbar-brand") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="d-flex navbar-nav me-auto mb-2 mb-lg-0"></ul>

      <div class="d-flex">
        <ul class="d-flex navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown no-arrow">
            <li class="nav-item dropdown">
              <% if user_signed_in? %>
              <li class="nav-item position-relative">
                <%= link_to "#", class: "nav-link" do %>
                  Hi, <%= current_user.email %>
                <% end %>
              </li>
              <li class="nav-item position-relative">
                <% if current_user.post.present? %>
                  <%= link_to preview_my_post_path, class: "nav-link" do %>
                    我的愛車
                  <% end %>
                <% else %>
                  <%= link_to new_my_post_path, class: "nav-link" do %>
                    新增愛車
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link") do %>
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  登出
                <% end %>
              </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to("註冊", vip_lobby_path, class: "nav-link") %>
                </li>
                <li class="nav-item">
                  <%= link_to("登入", new_user_session_path, class: "nav-link") %>
                </li>
              <% end %>
            </li>
          </li>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>


  <body id="page-top">
    <div id="wrapper">
      <%= render "common/flashes" %>

      <%= render "admin/common/sidebar" %>

      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render "admin/common/navbar" %>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "common/google_analytics" if Rails.env.production? %>
  </head>

  <body>
    <%= render "common/navbar" %>

    <div class="container-fluid">
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

      <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">
      @media print {
        #tableA2 {
          -webkit-print-color-adjust: exact;
        }
      }

      p {
        margin: 0;
        line-height: 1.5;
      }

      table:first-child {
        padding-bottom: 10px;
      }
    </style>
  </head>


  <body>
    <%= yield %>
  </body>
</html>