config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  resources :posts, only: [:index, :show]

  namespace :my do
    resource :post, only: [:new, :create, :edit, :update] do
      member do
        get :preview
        patch :submit
      end
    end
  end

  namespace :admin do
    resources :coupons do
      member do
        get :print
        patch :tag_sended
      end
      collection do
        post :batch_create
        get :bulk_print
      end
    end

    resources :users
    resources :posts do
      member do
        patch :approve
      end
    end

    root "dashboard#index"
  end

  get "vip_lobby", to: "home#vip_lobby"
  get "guide", to: "home#guide"
  post "enter_lobby", to: "home#enter_lobby"

  root "posts#index"
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  include AASM

  enum using_state: {
    initial: 0,
    complete: 1
  }

  belongs_to :user, optional: true

  before_create :generate_code

  aasm column: :using_state, enum: true do # defaults to aasm_state
    state :initial, initial: true
    state :complete

    event :complete do
      transitions to: :complete, from: [:initial]
    end
  end

  scope :recent, -> { order(id: :desc) }

  private

  def generate_code
    self.code = SecureRandom.hex(4).upcase
  end
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::BaseController
  def index
    @coupons = Coupon.all.recent
  end

  def batch_create
    total = 10

    total.times { Coupon.create! }

    redirect_back(fallback_location: admin_coupons_path, notice: "成功建立 #{total} 筆 Coupon")
  end

  def tag_sended
    @coupon = Coupon.find(params[:id])

    if @coupon.update(send_at_unixtime: Time.zone.now.to_i)
      redirect_back(fallback_location: admin_coupons_path, notice: "成功將 ID: #{@coupon.id} 送出給用戶！")
    else
      redirect_back(fallback_location: admin_coupons_path, notice: "失敗！ID: #{@coupon.id}")
    end
  end

  def print
    @coupon = Coupon.find(params[:id])

    @coupon.update(send_at_unixtime: Time.zone.now.to_i)

    render layout: "print"
  end

  def bulk_print
    total = 0

    @coupons = Coupon.where(id: params[:ids])

    @coupons.update(send_at_unixtime: Time.zone.now.to_i)

    render layout: "print"
  end
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/views/admin/coupons/_print_info.html.erb
<table cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <td style="border-top-width: 0px; border-left-width: 0px; border-bottom-width: 2px; border-right-width: 2px;">
        <div style="padding: 0px 2px 0px 2px; margin: 0 auto; float: middle; border-top: 0px; border-left: 0px; border: 2px solid #000000;
                    width: 450px; height: 150px;">
          <p style="text-align: center;
  font-weight: 600;">NLFS 便友通行證</p>
          <div style="display: inline-block; padding-left: 20px;">
            <% qrcode = RQRCode::QRCode.new("https://www.nlfs.tw/vip_lobby?coupon=#{coupon.code}") %>
            <%= qrcode.as_svg(
                color: "000",
                shape_rendering: "crispEdges",
                module_size: 2,
                standalone: true,
                use_path: true
              ).html_safe %>
          </div>

          <div style="display: inline-block; padding: 10px;">
            <p>便友獨享專屬網站曝光自己的愛車</p>
            <p>您可以掃 QR code 進行帳號註冊</p>
            <p>VIP 入口: https://www.nlfs.tw/vip_lobby </p>
            <p>專屬序號: <%= coupon.code %></p>
          </div>

        </div>
      </td>
      </td>
  </tbody>
</table>

app/views/admin/coupons/bulk_print.html.erb
<% @coupons.each do |coupon| %>
  <%= render partial: "print_info", locals: { coupon: coupon } %>
<% end %>

app/views/admin/coupons/index.html.erb
<%= link_to("建立 10 筆", batch_create_admin_coupons_path, class: "btn btn-primary", method: :post, data: { confirm: "確定建立 10 筆嗎？"}) %>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
    <%= form_tag bulk_print_admin_coupons_path, class: "form-inline", method: :get do %>
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>#</th>
            <th scope="col">ID</th>
            <th scope="col">序號</th>
            <th scope="col">狀態</th>
            <th scope="col">關聯 UserID</th>
            <th scope="col">送出時間</th>
          </tr>
        </thead>
        <tbody>
          <% @coupons.each do |coupon| %>
            <tr>
              <td><%= check_box_tag "ids[]", coupon.id %></td>
              <th><%= coupon.id %></th>
              <th><%= coupon.code %></th>
              <th><%= coupon.using_state %></th>
              <th><%= coupon.user_id %></th>
              <th><%= coupon.send_at_unixtime %></th>
              <th>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#couponModal-<%= coupon.id %>">
                  分享
                </button>
                <%= link_to("列印", print_admin_coupon_path(coupon), class: "btn btn-info", target: "_blank") %>
              </th>
            </tr>

            <div class="modal fade" id="couponModal-<%= coupon.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-body">
                    <p>感謝支持!!!</p>

                    <p>這是註冊序號</p>

                    <p><%= coupon.code %></p>

                    <p>一個序號可以註冊一筆帳號</p>

                    <p>一筆帳號只能發一篇文章而已</p>

                    <p>註冊入口在此</p>

                    <p>https://www.nlfs.tw/vip_lobby</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
                    <%= link_to("標示已送出", tag_sended_admin_coupon_path(coupon), class: "btn btn-primary", method: :patch, data: { confirm: "標記送出嗎？" }) %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </tbody>
      </table>

      <p><%= submit_tag "批次列印", class: "btn btn-danger", data: { confirm: "Are you sure?" } %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/coupons/print.html.erb
<%= render partial: "print_info", locals: { coupon: @coupon } %>